### PR TITLE
Spinx 1.7+ ImportError workaround

### LINKED ISSUE #66: ImportError: cannot import name 'build_main'
Using : 
* sphinx-2.2.0
* sphinxcontrib-versioning-2.2.1

While running any `sphinxcontrib-versioning` command, I got : 
```sh
$ sphinx-versioning build --help

...
File "~/.virtualenvs/docs-temp/lib/python3.6/site-packages/sphinxcontrib/versioning/sphinx_.py", line 9, in <module>
    from sphinx import application, build_main, locale
ImportError: cannot import name 'build_main'
```

It seems like a wrong module call because `build_main` is not in `sphinx` package but it  can be called from module `sphinx.cmd.build`.

Indeed, when I manually modify as below : 
```python
# versioning/sphinx_.py

from sphinx import build_main              # old line
from sphinx.cmd.build import build_main    # new line
```

everything seems to go well.

### PR DESCRIPTION
**Pull request by z00sts**
Allows you at least see application help instead of Traceback print.

Fixes #66

### CODE REVIEW

**Review by paddy-hack — COMMENTED** [review]
Misleading comment.  It's not the Python version that causes the ImportError.  It's upgrading Sphinx from 1.6.5 to 1.7.0 that does.  Suggest the comment gets fixed.
Applying the fix worked fine for me with Python 3.**4**.

**Comment by z00sts** [comment]
@paddy-hack thanks for clarification. So you closing the PR?

**Comment by paddy-hack** [comment]
No, I'm not closing this PR.  I'm just suggesting you fix up the comment in this/your PR so people looking at the code later don't get misled.  That's all.

See https://github.com/sphinx-contrib/sphinxcontrib-versioning/issues/70#issuecomment-554632618 for some background info on this.

**Comment by TimKam** [comment]
Can yo control-merge master into your branch/rebase, @z00sts? Also, if I understand it correctly, updating  `sphinxcontrib-versioning` without updating a very old Sphinx install (< 1.7) would cause problems given the changes in this PR, but IMHO we can live with this.

**Comment by z00sts** [comment]
I updated branch state with upstream and created new PR with correct branch-name and commit message https://github.com/sphinx-contrib/sphinxcontrib-versioning/pull/78

**Pull request closed without merging**
